### ISSUE TITLE
Migration options: React Native or pure Android

### ISSUE THREAD

**Issue by mgochoa** [camilo1822/proyectoIntegrador#5]
We have to analyze what are the best options:
In one hand, we have React Native and the possibility to make a cross-platform apps, even writing native code.
On the another hand we have the Native Language of Android and the power of new technologies such like Beacons and Instant Apps.

**Comment by camilosampedro** [comment]
I like the __React Native__ and the __Kotlin__ ones, is it possible to use Instant Apps with Kotlin? :sushi:

**Comment by mgochoa** [comment]
Sure, you can write native componentes with **Kotlin**, and export them as modules for your **React Native** app. Be aware, this is just theory but I'm reaserching a lot about the subject.

**Comment by mgochoa** [comment]
Closing this issue by the moment, it's decided it's gonna be migrated to Ionic 3. Just for showing purposes
